[versions]
plugin-api = "1.0.0"
android-gradle-plugin = "8.13.2"
kotlin = "2.2.21"

[libraries]
plugin-api = { group = "app.revanced", name = "revanced-manager-downloader-api", version.ref = "plugin-api" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
